import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from "node:module";
import fs from "fs";
import path from "path";

// Plugin to copy static files into the test vault whenever esbuild runs
const copyStaticFilesPlugin = {
    name: "copy-static-files",
    setup(build) {
        build.onEnd(() => {
            // Ensure the target plugin folder exists
            fs.mkdirSync(outdir, { recursive: true });

            // Copy manifest.json
            if (fs.existsSync("manifest.json")) {
                fs.copyFileSync("manifest.json", path.join(outdir, "manifest.json"));
            }

            // Copy styles.css if present
            if (fs.existsSync("styles.css")) {
                fs.copyFileSync("styles.css", path.join(outdir, "styles.css"));
            }

            console.log(`[build] Assets synced to ${outdir}`);
        });
    },
};

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
// esbuild.config.mjs
const outdir = "test-vault/.obsidian/plugins/obsidian-cairn";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules.flatMap((m) => [m, `node:${m}`]),
	],
	format: 'cjs',
	target: 'es2021',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: `${outdir}/main.js`,
	minify: prod,
	plugins: [copyStaticFilesPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
