import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import fs from 'fs';
import path from 'path';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const outdir = 'test-vault/.obsidian/plugins/obsidian-cairn';

// In dev mode, output to test-vault; in production/CI, output to repo root
const targetDir = prod ? '.' : outdir;

const copyStaticFilesPlugin = {
    name: 'copy-static-files',
    setup(build) {
        build.onEnd(() => {
            // Only sync assets into the test-vault during local dev
            if (!prod) {
                fs.mkdirSync(outdir, { recursive: true });

                if (fs.existsSync('manifest.json')) {
                    fs.copyFileSync('manifest.json', path.join(outdir, 'manifest.json'));
                }

                if (fs.existsSync('styles.css')) {
                    fs.copyFileSync('styles.css', path.join(outdir, 'styles.css'));
                }

                console.log(`[build] Assets synced to ${outdir}`);
            }
        });
    },
};

const context = await esbuild.context({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtinModules.flatMap((m) => [m, `node:${m}`]),
    ],
    format: 'cjs',
    target: 'es2021',
    logLevel: 'info',
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    outfile: path.join(targetDir, 'main.js'),
    minify: prod,
    plugins: [copyStaticFilesPlugin],
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}